[project]
name = "music-data-attribution"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "Paweł Kochański", email = "pawel.kochanski3.stud@pw.edu.pl"},
    {name = "Jakub Proboszcz", email = "jakub.proboszcz.stud@pw.edu.pl"},
    {name = "Mikołaj Piórczyński", email = "mikolaj.piorczynski.stud@pw.edu.pl"}
]
dependencies = ["einops>=0.8.1", "torch>=2.6.0", "torchaudio>=2.6.0", "torchcodec>=0.8.1", "audiocraft>=1.2.0", "ipykernel>=7.1.0"]

requires-python = "==3.11.*"
readme = "README.md"
license = {text = "MIT"}

[tool.pdm]
distribution = false

[tool.pdm.resolution.overrides]
numpy = ">=2.0.0,<=2.3.0"
pandas = ">=2.2.0"
pydantic = ">=2.0.0"
torch = ">=2.3.0"
torchvision = ">=0.21.0"
torchaudio = ">=2.2.0"
wandb = ">=0.20.0"

[[tool.pdm.source]]
name = "private"
url = "https://download.pytorch.org/whl/cu124"
include_packages = ["torch", "torchvision", "torchaudio", "xformers"]
exclude_packages = ["*"]

[tool.pdm.dev-dependencies]
dev = [
    "-e file:///${PROJECT_ROOT}/trak#egg=traker[fast]",
    "-e file:///${PROJECT_ROOT}#egg=music_data_attribution",
    "-e file:///${PROJECT_ROOT}/stable-audio-tools#egg=stable-audio-tools",
]

[tool.setuptools]
packages = ["music_data_attribution"]

[tool.ruff]
line-length = 120

[tool.mypy]
explicit_package_bases = true
ignore_missing_imports = true
exclude = "trak|stable-audio-tools"

[dependency-groups]
dev = [
    "mypy>=1.19.1",
    "pandas-stubs>=2.3.3.260113",
    "types-tqdm>=4.67.0.20250809",
    "ruff>=0.14.14",
]
